### PR TITLE
updated functional navbar

### PR DESCRIPTION
**Pull request by jorozco4**
Updated navbar

### CODE REVIEW

**Comment by vinicomelo** [comment]
Not running successfully. Looks like there's some error related to bootstrap?

image

**Comment by vinicomelo** [comment]
Could not get it to run, error:

image

**Comment by vinicomelo** [comment]
Ah so that's the problem, you must have installed bootstrap only locally to you. You need to update the package.json file to have it so when I run npm install, it will install it for me.

Remember you can always run 

npm install <package_name_here> --save to automatically update package.json

**Comment by jorozco4** [comment]
Ok cool.

**Pull request closed without merging**
